### ISSUE TITLE
Do something lazy bastard!

### ISSUE THREAD

**Issue by Mistra** [ABVitali/briscola#9]
Taken into account the scheme found [here](https://github.com/Mistra/briscola/blob/master/unnamed0.jpg) and bits of structure found in my forked repo:
1. Provide the necessary changes to the **Hand** class to fit the proposed model.
2. Update the schema definition for player_hand (database/schema.sql) accordingly.
3. Create a class **hand_repository** with two basic methods: create(hand: Hand) and find_by_id(hand_id: str)
4. Create under test/repository/test_hand_repository.py the class TestHandRepository(unittest.TestCase), with the two unit tests for the hand_repository above.

For point 3 (and 4) I **strongly** suggest exposing the injection of the database at repository constructor level. This way the injection of a simple _:memory:_ sqlite in the tests it's way easier.

Bonus challenge: should you decide to use the memory sqlite in the unit test, try to keep the SSOT reading the db schema from the database.sql file

**Comment by ABVitali** [comment]
Won't do

**Comment by Mistra** [comment]
closable pulling PR #10
